version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: live-state-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: live_state_test
    ports:
      - "5432:5432"
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
      - ./docker/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
